# Generated by Django 4.2.30 on 2026-09-04 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FlyNote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL),
        ),
    ]
